language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - apt-get update -qq
  - apt-get install xclip xsel --no-install-recommends --yes
  - export PATH="/usr/bin/:$PATH"

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script:
  - make test

after_script:
  - coveralls
