version: 2
jobs:
  build:
    working_directory: ~/pickleclip
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            sudo pip install -r requirements.test.txt
      - run:
          command: make test
